master:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  service:
    type: NodePort
    nodePorts:
      cluster: ""
      http: "30808"

worker:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

image:
  pullPolicy: Always
